// Hardware_Qsys.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module Hardware_Qsys (
		input  wire        clk_clk,           //        clk.clk
		output wire [31:0] hex3_hex0_export,  //  hex3_hex0.export
		output wire [15:0] hex5_hex4_export,  //  hex5_hex4.export
		input  wire        i2c_serial_sda_in, // i2c_serial.sda_in
		input  wire        i2c_serial_scl_in, //           .scl_in
		output wire        i2c_serial_sda_oe, //           .sda_oe
		output wire        i2c_serial_scl_oe, //           .scl_oe
		output wire [9:0]  ledr_export,       //       ledr.export
		input  wire [1:0]  pushbutton_export, // pushbutton.export
		input  wire        reset_reset_n,     //      reset.reset_n
		input  wire [9:0]  switch_export,     //     switch.export
		input  wire        uart_lidar_rxd,    // uart_lidar.rxd
		output wire        uart_lidar_txd,    //           .txd
		input  wire        uart_pc_rxd,       //    uart_pc.rxd
		output wire        uart_pc_txd        //           .txd
	);

	wire  [31:0] niosii_cpu_data_master_readdata;                             // mm_interconnect_0:NIOSII_CPU_data_master_readdata -> NIOSII_CPU:d_readdata
	wire         niosii_cpu_data_master_waitrequest;                          // mm_interconnect_0:NIOSII_CPU_data_master_waitrequest -> NIOSII_CPU:d_waitrequest
	wire         niosii_cpu_data_master_debugaccess;                          // NIOSII_CPU:debug_mem_slave_debugaccess_to_roms -> mm_interconnect_0:NIOSII_CPU_data_master_debugaccess
	wire  [18:0] niosii_cpu_data_master_address;                              // NIOSII_CPU:d_address -> mm_interconnect_0:NIOSII_CPU_data_master_address
	wire   [3:0] niosii_cpu_data_master_byteenable;                           // NIOSII_CPU:d_byteenable -> mm_interconnect_0:NIOSII_CPU_data_master_byteenable
	wire         niosii_cpu_data_master_read;                                 // NIOSII_CPU:d_read -> mm_interconnect_0:NIOSII_CPU_data_master_read
	wire         niosii_cpu_data_master_write;                                // NIOSII_CPU:d_write -> mm_interconnect_0:NIOSII_CPU_data_master_write
	wire  [31:0] niosii_cpu_data_master_writedata;                            // NIOSII_CPU:d_writedata -> mm_interconnect_0:NIOSII_CPU_data_master_writedata
	wire  [31:0] niosii_cpu_instruction_master_readdata;                      // mm_interconnect_0:NIOSII_CPU_instruction_master_readdata -> NIOSII_CPU:i_readdata
	wire         niosii_cpu_instruction_master_waitrequest;                   // mm_interconnect_0:NIOSII_CPU_instruction_master_waitrequest -> NIOSII_CPU:i_waitrequest
	wire  [18:0] niosii_cpu_instruction_master_address;                       // NIOSII_CPU:i_address -> mm_interconnect_0:NIOSII_CPU_instruction_master_address
	wire         niosii_cpu_instruction_master_read;                          // NIOSII_CPU:i_read -> mm_interconnect_0:NIOSII_CPU_instruction_master_read
	wire         niosii_cpu_instruction_master_readdatavalid;                 // mm_interconnect_0:NIOSII_CPU_instruction_master_readdatavalid -> NIOSII_CPU:i_readdatavalid
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_chipselect;  // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_chipselect -> jtag_uart_0:av_chipselect
	wire  [31:0] mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_readdata;    // jtag_uart_0:av_readdata -> mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_waitrequest; // jtag_uart_0:av_waitrequest -> mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_address;     // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_address -> jtag_uart_0:av_address
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_read;        // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_read -> jtag_uart_0:av_read_n
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_write;       // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_write -> jtag_uart_0:av_write_n
	wire  [31:0] mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_writedata;   // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_writedata -> jtag_uart_0:av_writedata
	wire  [31:0] mm_interconnect_0_sysid_qsys_0_control_slave_readdata;       // sysid_qsys_0:readdata -> mm_interconnect_0:sysid_qsys_0_control_slave_readdata
	wire   [0:0] mm_interconnect_0_sysid_qsys_0_control_slave_address;        // mm_interconnect_0:sysid_qsys_0_control_slave_address -> sysid_qsys_0:address
	wire  [31:0] mm_interconnect_0_i2c_csr_readdata;                          // I2C:readdata -> mm_interconnect_0:I2C_csr_readdata
	wire   [3:0] mm_interconnect_0_i2c_csr_address;                           // mm_interconnect_0:I2C_csr_address -> I2C:addr
	wire         mm_interconnect_0_i2c_csr_read;                              // mm_interconnect_0:I2C_csr_read -> I2C:read
	wire         mm_interconnect_0_i2c_csr_write;                             // mm_interconnect_0:I2C_csr_write -> I2C:write
	wire  [31:0] mm_interconnect_0_i2c_csr_writedata;                         // mm_interconnect_0:I2C_csr_writedata -> I2C:writedata
	wire  [31:0] mm_interconnect_0_niosii_cpu_debug_mem_slave_readdata;       // NIOSII_CPU:debug_mem_slave_readdata -> mm_interconnect_0:NIOSII_CPU_debug_mem_slave_readdata
	wire         mm_interconnect_0_niosii_cpu_debug_mem_slave_waitrequest;    // NIOSII_CPU:debug_mem_slave_waitrequest -> mm_interconnect_0:NIOSII_CPU_debug_mem_slave_waitrequest
	wire         mm_interconnect_0_niosii_cpu_debug_mem_slave_debugaccess;    // mm_interconnect_0:NIOSII_CPU_debug_mem_slave_debugaccess -> NIOSII_CPU:debug_mem_slave_debugaccess
	wire   [8:0] mm_interconnect_0_niosii_cpu_debug_mem_slave_address;        // mm_interconnect_0:NIOSII_CPU_debug_mem_slave_address -> NIOSII_CPU:debug_mem_slave_address
	wire         mm_interconnect_0_niosii_cpu_debug_mem_slave_read;           // mm_interconnect_0:NIOSII_CPU_debug_mem_slave_read -> NIOSII_CPU:debug_mem_slave_read
	wire   [3:0] mm_interconnect_0_niosii_cpu_debug_mem_slave_byteenable;     // mm_interconnect_0:NIOSII_CPU_debug_mem_slave_byteenable -> NIOSII_CPU:debug_mem_slave_byteenable
	wire         mm_interconnect_0_niosii_cpu_debug_mem_slave_write;          // mm_interconnect_0:NIOSII_CPU_debug_mem_slave_write -> NIOSII_CPU:debug_mem_slave_write
	wire  [31:0] mm_interconnect_0_niosii_cpu_debug_mem_slave_writedata;      // mm_interconnect_0:NIOSII_CPU_debug_mem_slave_writedata -> NIOSII_CPU:debug_mem_slave_writedata
	wire         mm_interconnect_0_memory_s1_chipselect;                      // mm_interconnect_0:MEMORY_s1_chipselect -> MEMORY:chipselect
	wire  [31:0] mm_interconnect_0_memory_s1_readdata;                        // MEMORY:readdata -> mm_interconnect_0:MEMORY_s1_readdata
	wire  [14:0] mm_interconnect_0_memory_s1_address;                         // mm_interconnect_0:MEMORY_s1_address -> MEMORY:address
	wire   [3:0] mm_interconnect_0_memory_s1_byteenable;                      // mm_interconnect_0:MEMORY_s1_byteenable -> MEMORY:byteenable
	wire         mm_interconnect_0_memory_s1_write;                           // mm_interconnect_0:MEMORY_s1_write -> MEMORY:write
	wire  [31:0] mm_interconnect_0_memory_s1_writedata;                       // mm_interconnect_0:MEMORY_s1_writedata -> MEMORY:writedata
	wire         mm_interconnect_0_memory_s1_clken;                           // mm_interconnect_0:MEMORY_s1_clken -> MEMORY:clken
	wire         mm_interconnect_0_timer_tof_s1_chipselect;                   // mm_interconnect_0:TIMER_TOF_s1_chipselect -> TIMER_TOF:chipselect
	wire  [15:0] mm_interconnect_0_timer_tof_s1_readdata;                     // TIMER_TOF:readdata -> mm_interconnect_0:TIMER_TOF_s1_readdata
	wire   [2:0] mm_interconnect_0_timer_tof_s1_address;                      // mm_interconnect_0:TIMER_TOF_s1_address -> TIMER_TOF:address
	wire         mm_interconnect_0_timer_tof_s1_write;                        // mm_interconnect_0:TIMER_TOF_s1_write -> TIMER_TOF:write_n
	wire  [15:0] mm_interconnect_0_timer_tof_s1_writedata;                    // mm_interconnect_0:TIMER_TOF_s1_writedata -> TIMER_TOF:writedata
	wire  [31:0] mm_interconnect_0_switch_s1_readdata;                        // SWITCH:readdata -> mm_interconnect_0:SWITCH_s1_readdata
	wire   [1:0] mm_interconnect_0_switch_s1_address;                         // mm_interconnect_0:SWITCH_s1_address -> SWITCH:address
	wire         mm_interconnect_0_pb_s1_chipselect;                          // mm_interconnect_0:PB_s1_chipselect -> PB:chipselect
	wire  [31:0] mm_interconnect_0_pb_s1_readdata;                            // PB:readdata -> mm_interconnect_0:PB_s1_readdata
	wire   [1:0] mm_interconnect_0_pb_s1_address;                             // mm_interconnect_0:PB_s1_address -> PB:address
	wire         mm_interconnect_0_pb_s1_write;                               // mm_interconnect_0:PB_s1_write -> PB:write_n
	wire  [31:0] mm_interconnect_0_pb_s1_writedata;                           // mm_interconnect_0:PB_s1_writedata -> PB:writedata
	wire         mm_interconnect_0_ledr_s1_chipselect;                        // mm_interconnect_0:LEDR_s1_chipselect -> LEDR:chipselect
	wire  [31:0] mm_interconnect_0_ledr_s1_readdata;                          // LEDR:readdata -> mm_interconnect_0:LEDR_s1_readdata
	wire   [1:0] mm_interconnect_0_ledr_s1_address;                           // mm_interconnect_0:LEDR_s1_address -> LEDR:address
	wire         mm_interconnect_0_ledr_s1_write;                             // mm_interconnect_0:LEDR_s1_write -> LEDR:write_n
	wire  [31:0] mm_interconnect_0_ledr_s1_writedata;                         // mm_interconnect_0:LEDR_s1_writedata -> LEDR:writedata
	wire         mm_interconnect_0_hex3_hex0_s1_chipselect;                   // mm_interconnect_0:HEX3_HEX0_s1_chipselect -> HEX3_HEX0:chipselect
	wire  [31:0] mm_interconnect_0_hex3_hex0_s1_readdata;                     // HEX3_HEX0:readdata -> mm_interconnect_0:HEX3_HEX0_s1_readdata
	wire   [1:0] mm_interconnect_0_hex3_hex0_s1_address;                      // mm_interconnect_0:HEX3_HEX0_s1_address -> HEX3_HEX0:address
	wire         mm_interconnect_0_hex3_hex0_s1_write;                        // mm_interconnect_0:HEX3_HEX0_s1_write -> HEX3_HEX0:write_n
	wire  [31:0] mm_interconnect_0_hex3_hex0_s1_writedata;                    // mm_interconnect_0:HEX3_HEX0_s1_writedata -> HEX3_HEX0:writedata
	wire         mm_interconnect_0_hex5_hex4_s1_chipselect;                   // mm_interconnect_0:HEX5_HEX4_s1_chipselect -> HEX5_HEX4:chipselect
	wire  [31:0] mm_interconnect_0_hex5_hex4_s1_readdata;                     // HEX5_HEX4:readdata -> mm_interconnect_0:HEX5_HEX4_s1_readdata
	wire   [1:0] mm_interconnect_0_hex5_hex4_s1_address;                      // mm_interconnect_0:HEX5_HEX4_s1_address -> HEX5_HEX4:address
	wire         mm_interconnect_0_hex5_hex4_s1_write;                        // mm_interconnect_0:HEX5_HEX4_s1_write -> HEX5_HEX4:write_n
	wire  [31:0] mm_interconnect_0_hex5_hex4_s1_writedata;                    // mm_interconnect_0:HEX5_HEX4_s1_writedata -> HEX5_HEX4:writedata
	wire         mm_interconnect_0_uart_pc_s1_chipselect;                     // mm_interconnect_0:UART_PC_s1_chipselect -> UART_PC:chipselect
	wire  [15:0] mm_interconnect_0_uart_pc_s1_readdata;                       // UART_PC:readdata -> mm_interconnect_0:UART_PC_s1_readdata
	wire   [2:0] mm_interconnect_0_uart_pc_s1_address;                        // mm_interconnect_0:UART_PC_s1_address -> UART_PC:address
	wire         mm_interconnect_0_uart_pc_s1_read;                           // mm_interconnect_0:UART_PC_s1_read -> UART_PC:read_n
	wire         mm_interconnect_0_uart_pc_s1_begintransfer;                  // mm_interconnect_0:UART_PC_s1_begintransfer -> UART_PC:begintransfer
	wire         mm_interconnect_0_uart_pc_s1_write;                          // mm_interconnect_0:UART_PC_s1_write -> UART_PC:write_n
	wire  [15:0] mm_interconnect_0_uart_pc_s1_writedata;                      // mm_interconnect_0:UART_PC_s1_writedata -> UART_PC:writedata
	wire         mm_interconnect_0_uart_lidar_s1_chipselect;                  // mm_interconnect_0:UART_LIDAR_s1_chipselect -> UART_LIDAR:chipselect
	wire  [15:0] mm_interconnect_0_uart_lidar_s1_readdata;                    // UART_LIDAR:readdata -> mm_interconnect_0:UART_LIDAR_s1_readdata
	wire   [2:0] mm_interconnect_0_uart_lidar_s1_address;                     // mm_interconnect_0:UART_LIDAR_s1_address -> UART_LIDAR:address
	wire         mm_interconnect_0_uart_lidar_s1_read;                        // mm_interconnect_0:UART_LIDAR_s1_read -> UART_LIDAR:read_n
	wire         mm_interconnect_0_uart_lidar_s1_begintransfer;               // mm_interconnect_0:UART_LIDAR_s1_begintransfer -> UART_LIDAR:begintransfer
	wire         mm_interconnect_0_uart_lidar_s1_write;                       // mm_interconnect_0:UART_LIDAR_s1_write -> UART_LIDAR:write_n
	wire  [15:0] mm_interconnect_0_uart_lidar_s1_writedata;                   // mm_interconnect_0:UART_LIDAR_s1_writedata -> UART_LIDAR:writedata
	wire         mm_interconnect_0_timer_imu_s1_chipselect;                   // mm_interconnect_0:TIMER_IMU_s1_chipselect -> TIMER_IMU:chipselect
	wire  [15:0] mm_interconnect_0_timer_imu_s1_readdata;                     // TIMER_IMU:readdata -> mm_interconnect_0:TIMER_IMU_s1_readdata
	wire   [2:0] mm_interconnect_0_timer_imu_s1_address;                      // mm_interconnect_0:TIMER_IMU_s1_address -> TIMER_IMU:address
	wire         mm_interconnect_0_timer_imu_s1_write;                        // mm_interconnect_0:TIMER_IMU_s1_write -> TIMER_IMU:write_n
	wire  [15:0] mm_interconnect_0_timer_imu_s1_writedata;                    // mm_interconnect_0:TIMER_IMU_s1_writedata -> TIMER_IMU:writedata
	wire         irq_mapper_receiver0_irq;                                    // I2C:intr -> irq_mapper:receiver0_irq
	wire         irq_mapper_receiver1_irq;                                    // jtag_uart_0:av_irq -> irq_mapper:receiver1_irq
	wire         irq_mapper_receiver2_irq;                                    // TIMER_TOF:irq -> irq_mapper:receiver2_irq
	wire         irq_mapper_receiver3_irq;                                    // PB:irq -> irq_mapper:receiver3_irq
	wire         irq_mapper_receiver4_irq;                                    // UART_PC:irq -> irq_mapper:receiver4_irq
	wire         irq_mapper_receiver5_irq;                                    // UART_LIDAR:irq -> irq_mapper:receiver5_irq
	wire         irq_mapper_receiver6_irq;                                    // TIMER_IMU:irq -> irq_mapper:receiver6_irq
	wire  [31:0] niosii_cpu_irq_irq;                                          // irq_mapper:sender_irq -> NIOSII_CPU:irq
	wire         rst_controller_reset_out_reset;                              // rst_controller:reset_out -> [HEX3_HEX0:reset_n, HEX5_HEX4:reset_n, I2C:rst_n, LEDR:reset_n, PB:reset_n, SWITCH:reset_n, TIMER_IMU:reset_n, TIMER_TOF:reset_n, UART_LIDAR:reset_n, UART_PC:reset_n, jtag_uart_0:rst_n, mm_interconnect_0:jtag_uart_0_reset_reset_bridge_in_reset_reset, sysid_qsys_0:reset_n]
	wire         rst_controller_001_reset_out_reset;                          // rst_controller_001:reset_out -> [MEMORY:reset, NIOSII_CPU:reset_n, irq_mapper:reset, mm_interconnect_0:NIOSII_CPU_reset_reset_bridge_in_reset_reset]
	wire         rst_controller_001_reset_out_reset_req;                      // rst_controller_001:reset_req -> [MEMORY:reset_req, NIOSII_CPU:reset_req, rst_translator:reset_req_in]
	wire         niosii_cpu_debug_reset_request_reset;                        // NIOSII_CPU:debug_reset_request -> rst_controller_001:reset_in1

	Hardware_Qsys_HEX3_HEX0 hex3_hex0 (
		.clk        (clk_clk),                                   //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),           //               reset.reset_n
		.address    (mm_interconnect_0_hex3_hex0_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_hex3_hex0_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_hex3_hex0_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_hex3_hex0_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_hex3_hex0_s1_readdata),   //                    .readdata
		.out_port   (hex3_hex0_export)                           // external_connection.export
	);

	Hardware_Qsys_HEX5_HEX4 hex5_hex4 (
		.clk        (clk_clk),                                   //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),           //               reset.reset_n
		.address    (mm_interconnect_0_hex5_hex4_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_hex5_hex4_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_hex5_hex4_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_hex5_hex4_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_hex5_hex4_s1_readdata),   //                    .readdata
		.out_port   (hex5_hex4_export)                           // external_connection.export
	);

	altera_avalon_i2c #(
		.USE_AV_ST       (0),
		.FIFO_DEPTH      (8),
		.FIFO_DEPTH_LOG2 (3)
	) i2c (
		.clk       (clk_clk),                             //            clock.clk
		.rst_n     (~rst_controller_reset_out_reset),     //       reset_sink.reset_n
		.intr      (irq_mapper_receiver0_irq),            // interrupt_sender.irq
		.addr      (mm_interconnect_0_i2c_csr_address),   //              csr.address
		.read      (mm_interconnect_0_i2c_csr_read),      //                 .read
		.write     (mm_interconnect_0_i2c_csr_write),     //                 .write
		.writedata (mm_interconnect_0_i2c_csr_writedata), //                 .writedata
		.readdata  (mm_interconnect_0_i2c_csr_readdata),  //                 .readdata
		.sda_in    (i2c_serial_sda_in),                   //       i2c_serial.sda_in
		.scl_in    (i2c_serial_scl_in),                   //                 .scl_in
		.sda_oe    (i2c_serial_sda_oe),                   //                 .sda_oe
		.scl_oe    (i2c_serial_scl_oe),                   //                 .scl_oe
		.src_data  (),                                    //      (terminated)
		.src_valid (),                                    //      (terminated)
		.src_ready (1'b0),                                //      (terminated)
		.snk_data  (16'b0000000000000000),                //      (terminated)
		.snk_valid (1'b0),                                //      (terminated)
		.snk_ready ()                                     //      (terminated)
	);

	Hardware_Qsys_LEDR ledr (
		.clk        (clk_clk),                              //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),      //               reset.reset_n
		.address    (mm_interconnect_0_ledr_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_ledr_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_ledr_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_ledr_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_ledr_s1_readdata),   //                    .readdata
		.out_port   (ledr_export)                           // external_connection.export
	);

	Hardware_Qsys_MEMORY memory (
		.clk        (clk_clk),                                //   clk1.clk
		.address    (mm_interconnect_0_memory_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_memory_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_memory_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_memory_s1_write),      //       .write
		.readdata   (mm_interconnect_0_memory_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_memory_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_memory_s1_byteenable), //       .byteenable
		.reset      (rst_controller_001_reset_out_reset),     // reset1.reset
		.reset_req  (rst_controller_001_reset_out_reset_req), //       .reset_req
		.freeze     (1'b0)                                    // (terminated)
	);

	Hardware_Qsys_NIOSII_CPU niosii_cpu (
		.clk                                 (clk_clk),                                                  //                       clk.clk
		.reset_n                             (~rst_controller_001_reset_out_reset),                      //                     reset.reset_n
		.reset_req                           (rst_controller_001_reset_out_reset_req),                   //                          .reset_req
		.d_address                           (niosii_cpu_data_master_address),                           //               data_master.address
		.d_byteenable                        (niosii_cpu_data_master_byteenable),                        //                          .byteenable
		.d_read                              (niosii_cpu_data_master_read),                              //                          .read
		.d_readdata                          (niosii_cpu_data_master_readdata),                          //                          .readdata
		.d_waitrequest                       (niosii_cpu_data_master_waitrequest),                       //                          .waitrequest
		.d_write                             (niosii_cpu_data_master_write),                             //                          .write
		.d_writedata                         (niosii_cpu_data_master_writedata),                         //                          .writedata
		.debug_mem_slave_debugaccess_to_roms (niosii_cpu_data_master_debugaccess),                       //                          .debugaccess
		.i_address                           (niosii_cpu_instruction_master_address),                    //        instruction_master.address
		.i_read                              (niosii_cpu_instruction_master_read),                       //                          .read
		.i_readdata                          (niosii_cpu_instruction_master_readdata),                   //                          .readdata
		.i_waitrequest                       (niosii_cpu_instruction_master_waitrequest),                //                          .waitrequest
		.i_readdatavalid                     (niosii_cpu_instruction_master_readdatavalid),              //                          .readdatavalid
		.irq                                 (niosii_cpu_irq_irq),                                       //                       irq.irq
		.debug_reset_request                 (niosii_cpu_debug_reset_request_reset),                     //       debug_reset_request.reset
		.debug_mem_slave_address             (mm_interconnect_0_niosii_cpu_debug_mem_slave_address),     //           debug_mem_slave.address
		.debug_mem_slave_byteenable          (mm_interconnect_0_niosii_cpu_debug_mem_slave_byteenable),  //                          .byteenable
		.debug_mem_slave_debugaccess         (mm_interconnect_0_niosii_cpu_debug_mem_slave_debugaccess), //                          .debugaccess
		.debug_mem_slave_read                (mm_interconnect_0_niosii_cpu_debug_mem_slave_read),        //                          .read
		.debug_mem_slave_readdata            (mm_interconnect_0_niosii_cpu_debug_mem_slave_readdata),    //                          .readdata
		.debug_mem_slave_waitrequest         (mm_interconnect_0_niosii_cpu_debug_mem_slave_waitrequest), //                          .waitrequest
		.debug_mem_slave_write               (mm_interconnect_0_niosii_cpu_debug_mem_slave_write),       //                          .write
		.debug_mem_slave_writedata           (mm_interconnect_0_niosii_cpu_debug_mem_slave_writedata),   //                          .writedata
		.dummy_ci_port                       ()                                                          // custom_instruction_master.readra
	);

	Hardware_Qsys_PB pb (
		.clk        (clk_clk),                            //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),    //               reset.reset_n
		.address    (mm_interconnect_0_pb_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pb_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pb_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pb_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pb_s1_readdata),   //                    .readdata
		.in_port    (pushbutton_export),                  // external_connection.export
		.irq        (irq_mapper_receiver3_irq)            //                 irq.irq
	);

	Hardware_Qsys_SWITCH switch (
		.clk      (clk_clk),                              //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),      //               reset.reset_n
		.address  (mm_interconnect_0_switch_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_switch_s1_readdata), //                    .readdata
		.in_port  (switch_export)                         // external_connection.export
	);

	Hardware_Qsys_TIMER_IMU timer_imu (
		.clk        (clk_clk),                                   //   clk.clk
		.reset_n    (~rst_controller_reset_out_reset),           // reset.reset_n
		.address    (mm_interconnect_0_timer_imu_s1_address),    //    s1.address
		.writedata  (mm_interconnect_0_timer_imu_s1_writedata),  //      .writedata
		.readdata   (mm_interconnect_0_timer_imu_s1_readdata),   //      .readdata
		.chipselect (mm_interconnect_0_timer_imu_s1_chipselect), //      .chipselect
		.write_n    (~mm_interconnect_0_timer_imu_s1_write),     //      .write_n
		.irq        (irq_mapper_receiver6_irq)                   //   irq.irq
	);

	Hardware_Qsys_TIMER_IMU timer_tof (
		.clk        (clk_clk),                                   //   clk.clk
		.reset_n    (~rst_controller_reset_out_reset),           // reset.reset_n
		.address    (mm_interconnect_0_timer_tof_s1_address),    //    s1.address
		.writedata  (mm_interconnect_0_timer_tof_s1_writedata),  //      .writedata
		.readdata   (mm_interconnect_0_timer_tof_s1_readdata),   //      .readdata
		.chipselect (mm_interconnect_0_timer_tof_s1_chipselect), //      .chipselect
		.write_n    (~mm_interconnect_0_timer_tof_s1_write),     //      .write_n
		.irq        (irq_mapper_receiver2_irq)                   //   irq.irq
	);

	Hardware_Qsys_UART_LIDAR uart_lidar (
		.clk           (clk_clk),                                       //                 clk.clk
		.reset_n       (~rst_controller_reset_out_reset),               //               reset.reset_n
		.address       (mm_interconnect_0_uart_lidar_s1_address),       //                  s1.address
		.begintransfer (mm_interconnect_0_uart_lidar_s1_begintransfer), //                    .begintransfer
		.chipselect    (mm_interconnect_0_uart_lidar_s1_chipselect),    //                    .chipselect
		.read_n        (~mm_interconnect_0_uart_lidar_s1_read),         //                    .read_n
		.write_n       (~mm_interconnect_0_uart_lidar_s1_write),        //                    .write_n
		.writedata     (mm_interconnect_0_uart_lidar_s1_writedata),     //                    .writedata
		.readdata      (mm_interconnect_0_uart_lidar_s1_readdata),      //                    .readdata
		.rxd           (uart_lidar_rxd),                                // external_connection.export
		.txd           (uart_lidar_txd),                                //                    .export
		.irq           (irq_mapper_receiver5_irq)                       //                 irq.irq
	);

	Hardware_Qsys_UART_LIDAR uart_pc (
		.clk           (clk_clk),                                    //                 clk.clk
		.reset_n       (~rst_controller_reset_out_reset),            //               reset.reset_n
		.address       (mm_interconnect_0_uart_pc_s1_address),       //                  s1.address
		.begintransfer (mm_interconnect_0_uart_pc_s1_begintransfer), //                    .begintransfer
		.chipselect    (mm_interconnect_0_uart_pc_s1_chipselect),    //                    .chipselect
		.read_n        (~mm_interconnect_0_uart_pc_s1_read),         //                    .read_n
		.write_n       (~mm_interconnect_0_uart_pc_s1_write),        //                    .write_n
		.writedata     (mm_interconnect_0_uart_pc_s1_writedata),     //                    .writedata
		.readdata      (mm_interconnect_0_uart_pc_s1_readdata),      //                    .readdata
		.rxd           (uart_pc_rxd),                                // external_connection.export
		.txd           (uart_pc_txd),                                //                    .export
		.irq           (irq_mapper_receiver4_irq)                    //                 irq.irq
	);

	Hardware_Qsys_jtag_uart_0 jtag_uart_0 (
		.clk            (clk_clk),                                                     //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                             //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver1_irq)                                     //               irq.irq
	);

	Hardware_Qsys_sysid_qsys_0 sysid_qsys_0 (
		.clock    (clk_clk),                                               //           clk.clk
		.reset_n  (~rst_controller_reset_out_reset),                       //         reset.reset_n
		.readdata (mm_interconnect_0_sysid_qsys_0_control_slave_readdata), // control_slave.readdata
		.address  (mm_interconnect_0_sysid_qsys_0_control_slave_address)   //              .address
	);

	Hardware_Qsys_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                                 (clk_clk),                                                     //                               clk_0_clk.clk
		.jtag_uart_0_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                              // jtag_uart_0_reset_reset_bridge_in_reset.reset
		.NIOSII_CPU_reset_reset_bridge_in_reset_reset  (rst_controller_001_reset_out_reset),                          //  NIOSII_CPU_reset_reset_bridge_in_reset.reset
		.NIOSII_CPU_data_master_address                (niosii_cpu_data_master_address),                              //                  NIOSII_CPU_data_master.address
		.NIOSII_CPU_data_master_waitrequest            (niosii_cpu_data_master_waitrequest),                          //                                        .waitrequest
		.NIOSII_CPU_data_master_byteenable             (niosii_cpu_data_master_byteenable),                           //                                        .byteenable
		.NIOSII_CPU_data_master_read                   (niosii_cpu_data_master_read),                                 //                                        .read
		.NIOSII_CPU_data_master_readdata               (niosii_cpu_data_master_readdata),                             //                                        .readdata
		.NIOSII_CPU_data_master_write                  (niosii_cpu_data_master_write),                                //                                        .write
		.NIOSII_CPU_data_master_writedata              (niosii_cpu_data_master_writedata),                            //                                        .writedata
		.NIOSII_CPU_data_master_debugaccess            (niosii_cpu_data_master_debugaccess),                          //                                        .debugaccess
		.NIOSII_CPU_instruction_master_address         (niosii_cpu_instruction_master_address),                       //           NIOSII_CPU_instruction_master.address
		.NIOSII_CPU_instruction_master_waitrequest     (niosii_cpu_instruction_master_waitrequest),                   //                                        .waitrequest
		.NIOSII_CPU_instruction_master_read            (niosii_cpu_instruction_master_read),                          //                                        .read
		.NIOSII_CPU_instruction_master_readdata        (niosii_cpu_instruction_master_readdata),                      //                                        .readdata
		.NIOSII_CPU_instruction_master_readdatavalid   (niosii_cpu_instruction_master_readdatavalid),                 //                                        .readdatavalid
		.HEX3_HEX0_s1_address                          (mm_interconnect_0_hex3_hex0_s1_address),                      //                            HEX3_HEX0_s1.address
		.HEX3_HEX0_s1_write                            (mm_interconnect_0_hex3_hex0_s1_write),                        //                                        .write
		.HEX3_HEX0_s1_readdata                         (mm_interconnect_0_hex3_hex0_s1_readdata),                     //                                        .readdata
		.HEX3_HEX0_s1_writedata                        (mm_interconnect_0_hex3_hex0_s1_writedata),                    //                                        .writedata
		.HEX3_HEX0_s1_chipselect                       (mm_interconnect_0_hex3_hex0_s1_chipselect),                   //                                        .chipselect
		.HEX5_HEX4_s1_address                          (mm_interconnect_0_hex5_hex4_s1_address),                      //                            HEX5_HEX4_s1.address
		.HEX5_HEX4_s1_write                            (mm_interconnect_0_hex5_hex4_s1_write),                        //                                        .write
		.HEX5_HEX4_s1_readdata                         (mm_interconnect_0_hex5_hex4_s1_readdata),                     //                                        .readdata
		.HEX5_HEX4_s1_writedata                        (mm_interconnect_0_hex5_hex4_s1_writedata),                    //                                        .writedata
		.HEX5_HEX4_s1_chipselect                       (mm_interconnect_0_hex5_hex4_s1_chipselect),                   //                                        .chipselect
		.I2C_csr_address                               (mm_interconnect_0_i2c_csr_address),                           //                                 I2C_csr.address
		.I2C_csr_write                                 (mm_interconnect_0_i2c_csr_write),                             //                                        .write
		.I2C_csr_read                                  (mm_interconnect_0_i2c_csr_read),                              //                                        .read
		.I2C_csr_readdata                              (mm_interconnect_0_i2c_csr_readdata),                          //                                        .readdata
		.I2C_csr_writedata                             (mm_interconnect_0_i2c_csr_writedata),                         //                                        .writedata
		.jtag_uart_0_avalon_jtag_slave_address         (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_address),     //           jtag_uart_0_avalon_jtag_slave.address
		.jtag_uart_0_avalon_jtag_slave_write           (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_write),       //                                        .write
		.jtag_uart_0_avalon_jtag_slave_read            (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_read),        //                                        .read
		.jtag_uart_0_avalon_jtag_slave_readdata        (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_readdata),    //                                        .readdata
		.jtag_uart_0_avalon_jtag_slave_writedata       (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_writedata),   //                                        .writedata
		.jtag_uart_0_avalon_jtag_slave_waitrequest     (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_waitrequest), //                                        .waitrequest
		.jtag_uart_0_avalon_jtag_slave_chipselect      (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_chipselect),  //                                        .chipselect
		.LEDR_s1_address                               (mm_interconnect_0_ledr_s1_address),                           //                                 LEDR_s1.address
		.LEDR_s1_write                                 (mm_interconnect_0_ledr_s1_write),                             //                                        .write
		.LEDR_s1_readdata                              (mm_interconnect_0_ledr_s1_readdata),                          //                                        .readdata
		.LEDR_s1_writedata                             (mm_interconnect_0_ledr_s1_writedata),                         //                                        .writedata
		.LEDR_s1_chipselect                            (mm_interconnect_0_ledr_s1_chipselect),                        //                                        .chipselect
		.MEMORY_s1_address                             (mm_interconnect_0_memory_s1_address),                         //                               MEMORY_s1.address
		.MEMORY_s1_write                               (mm_interconnect_0_memory_s1_write),                           //                                        .write
		.MEMORY_s1_readdata                            (mm_interconnect_0_memory_s1_readdata),                        //                                        .readdata
		.MEMORY_s1_writedata                           (mm_interconnect_0_memory_s1_writedata),                       //                                        .writedata
		.MEMORY_s1_byteenable                          (mm_interconnect_0_memory_s1_byteenable),                      //                                        .byteenable
		.MEMORY_s1_chipselect                          (mm_interconnect_0_memory_s1_chipselect),                      //                                        .chipselect
		.MEMORY_s1_clken                               (mm_interconnect_0_memory_s1_clken),                           //                                        .clken
		.NIOSII_CPU_debug_mem_slave_address            (mm_interconnect_0_niosii_cpu_debug_mem_slave_address),        //              NIOSII_CPU_debug_mem_slave.address
		.NIOSII_CPU_debug_mem_slave_write              (mm_interconnect_0_niosii_cpu_debug_mem_slave_write),          //                                        .write
		.NIOSII_CPU_debug_mem_slave_read               (mm_interconnect_0_niosii_cpu_debug_mem_slave_read),           //                                        .read
		.NIOSII_CPU_debug_mem_slave_readdata           (mm_interconnect_0_niosii_cpu_debug_mem_slave_readdata),       //                                        .readdata
		.NIOSII_CPU_debug_mem_slave_writedata          (mm_interconnect_0_niosii_cpu_debug_mem_slave_writedata),      //                                        .writedata
		.NIOSII_CPU_debug_mem_slave_byteenable         (mm_interconnect_0_niosii_cpu_debug_mem_slave_byteenable),     //                                        .byteenable
		.NIOSII_CPU_debug_mem_slave_waitrequest        (mm_interconnect_0_niosii_cpu_debug_mem_slave_waitrequest),    //                                        .waitrequest
		.NIOSII_CPU_debug_mem_slave_debugaccess        (mm_interconnect_0_niosii_cpu_debug_mem_slave_debugaccess),    //                                        .debugaccess
		.PB_s1_address                                 (mm_interconnect_0_pb_s1_address),                             //                                   PB_s1.address
		.PB_s1_write                                   (mm_interconnect_0_pb_s1_write),                               //                                        .write
		.PB_s1_readdata                                (mm_interconnect_0_pb_s1_readdata),                            //                                        .readdata
		.PB_s1_writedata                               (mm_interconnect_0_pb_s1_writedata),                           //                                        .writedata
		.PB_s1_chipselect                              (mm_interconnect_0_pb_s1_chipselect),                          //                                        .chipselect
		.SWITCH_s1_address                             (mm_interconnect_0_switch_s1_address),                         //                               SWITCH_s1.address
		.SWITCH_s1_readdata                            (mm_interconnect_0_switch_s1_readdata),                        //                                        .readdata
		.sysid_qsys_0_control_slave_address            (mm_interconnect_0_sysid_qsys_0_control_slave_address),        //              sysid_qsys_0_control_slave.address
		.sysid_qsys_0_control_slave_readdata           (mm_interconnect_0_sysid_qsys_0_control_slave_readdata),       //                                        .readdata
		.TIMER_IMU_s1_address                          (mm_interconnect_0_timer_imu_s1_address),                      //                            TIMER_IMU_s1.address
		.TIMER_IMU_s1_write                            (mm_interconnect_0_timer_imu_s1_write),                        //                                        .write
		.TIMER_IMU_s1_readdata                         (mm_interconnect_0_timer_imu_s1_readdata),                     //                                        .readdata
		.TIMER_IMU_s1_writedata                        (mm_interconnect_0_timer_imu_s1_writedata),                    //                                        .writedata
		.TIMER_IMU_s1_chipselect                       (mm_interconnect_0_timer_imu_s1_chipselect),                   //                                        .chipselect
		.TIMER_TOF_s1_address                          (mm_interconnect_0_timer_tof_s1_address),                      //                            TIMER_TOF_s1.address
		.TIMER_TOF_s1_write                            (mm_interconnect_0_timer_tof_s1_write),                        //                                        .write
		.TIMER_TOF_s1_readdata                         (mm_interconnect_0_timer_tof_s1_readdata),                     //                                        .readdata
		.TIMER_TOF_s1_writedata                        (mm_interconnect_0_timer_tof_s1_writedata),                    //                                        .writedata
		.TIMER_TOF_s1_chipselect                       (mm_interconnect_0_timer_tof_s1_chipselect),                   //                                        .chipselect
		.UART_LIDAR_s1_address                         (mm_interconnect_0_uart_lidar_s1_address),                     //                           UART_LIDAR_s1.address
		.UART_LIDAR_s1_write                           (mm_interconnect_0_uart_lidar_s1_write),                       //                                        .write
		.UART_LIDAR_s1_read                            (mm_interconnect_0_uart_lidar_s1_read),                        //                                        .read
		.UART_LIDAR_s1_readdata                        (mm_interconnect_0_uart_lidar_s1_readdata),                    //                                        .readdata
		.UART_LIDAR_s1_writedata                       (mm_interconnect_0_uart_lidar_s1_writedata),                   //                                        .writedata
		.UART_LIDAR_s1_begintransfer                   (mm_interconnect_0_uart_lidar_s1_begintransfer),               //                                        .begintransfer
		.UART_LIDAR_s1_chipselect                      (mm_interconnect_0_uart_lidar_s1_chipselect),                  //                                        .chipselect
		.UART_PC_s1_address                            (mm_interconnect_0_uart_pc_s1_address),                        //                              UART_PC_s1.address
		.UART_PC_s1_write                              (mm_interconnect_0_uart_pc_s1_write),                          //                                        .write
		.UART_PC_s1_read                               (mm_interconnect_0_uart_pc_s1_read),                           //                                        .read
		.UART_PC_s1_readdata                           (mm_interconnect_0_uart_pc_s1_readdata),                       //                                        .readdata
		.UART_PC_s1_writedata                          (mm_interconnect_0_uart_pc_s1_writedata),                      //                                        .writedata
		.UART_PC_s1_begintransfer                      (mm_interconnect_0_uart_pc_s1_begintransfer),                  //                                        .begintransfer
		.UART_PC_s1_chipselect                         (mm_interconnect_0_uart_pc_s1_chipselect)                      //                                        .chipselect
	);

	Hardware_Qsys_irq_mapper irq_mapper (
		.clk           (clk_clk),                            //       clk.clk
		.reset         (rst_controller_001_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),           // receiver0.irq
		.receiver1_irq (irq_mapper_receiver1_irq),           // receiver1.irq
		.receiver2_irq (irq_mapper_receiver2_irq),           // receiver2.irq
		.receiver3_irq (irq_mapper_receiver3_irq),           // receiver3.irq
		.receiver4_irq (irq_mapper_receiver4_irq),           // receiver4.irq
		.receiver5_irq (irq_mapper_receiver5_irq),           // receiver5.irq
		.receiver6_irq (irq_mapper_receiver6_irq),           // receiver6.irq
		.sender_irq    (niosii_cpu_irq_irq)                  //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                 // reset_in0.reset
		.clk            (clk_clk),                        //       clk.clk
		.reset_out      (rst_controller_reset_out_reset), // reset_out.reset
		.reset_req      (),                               // (terminated)
		.reset_req_in0  (1'b0),                           // (terminated)
		.reset_in1      (1'b0),                           // (terminated)
		.reset_req_in1  (1'b0),                           // (terminated)
		.reset_in2      (1'b0),                           // (terminated)
		.reset_req_in2  (1'b0),                           // (terminated)
		.reset_in3      (1'b0),                           // (terminated)
		.reset_req_in3  (1'b0),                           // (terminated)
		.reset_in4      (1'b0),                           // (terminated)
		.reset_req_in4  (1'b0),                           // (terminated)
		.reset_in5      (1'b0),                           // (terminated)
		.reset_req_in5  (1'b0),                           // (terminated)
		.reset_in6      (1'b0),                           // (terminated)
		.reset_req_in6  (1'b0),                           // (terminated)
		.reset_in7      (1'b0),                           // (terminated)
		.reset_req_in7  (1'b0),                           // (terminated)
		.reset_in8      (1'b0),                           // (terminated)
		.reset_req_in8  (1'b0),                           // (terminated)
		.reset_in9      (1'b0),                           // (terminated)
		.reset_req_in9  (1'b0),                           // (terminated)
		.reset_in10     (1'b0),                           // (terminated)
		.reset_req_in10 (1'b0),                           // (terminated)
		.reset_in11     (1'b0),                           // (terminated)
		.reset_req_in11 (1'b0),                           // (terminated)
		.reset_in12     (1'b0),                           // (terminated)
		.reset_req_in12 (1'b0),                           // (terminated)
		.reset_in13     (1'b0),                           // (terminated)
		.reset_req_in13 (1'b0),                           // (terminated)
		.reset_in14     (1'b0),                           // (terminated)
		.reset_req_in14 (1'b0),                           // (terminated)
		.reset_in15     (1'b0),                           // (terminated)
		.reset_req_in15 (1'b0)                            // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~reset_reset_n),                         // reset_in0.reset
		.reset_in1      (niosii_cpu_debug_reset_request_reset),   // reset_in1.reset
		.clk            (clk_clk),                                //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_001_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                                   // (terminated)
		.reset_req_in1  (1'b0),                                   // (terminated)
		.reset_in2      (1'b0),                                   // (terminated)
		.reset_req_in2  (1'b0),                                   // (terminated)
		.reset_in3      (1'b0),                                   // (terminated)
		.reset_req_in3  (1'b0),                                   // (terminated)
		.reset_in4      (1'b0),                                   // (terminated)
		.reset_req_in4  (1'b0),                                   // (terminated)
		.reset_in5      (1'b0),                                   // (terminated)
		.reset_req_in5  (1'b0),                                   // (terminated)
		.reset_in6      (1'b0),                                   // (terminated)
		.reset_req_in6  (1'b0),                                   // (terminated)
		.reset_in7      (1'b0),                                   // (terminated)
		.reset_req_in7  (1'b0),                                   // (terminated)
		.reset_in8      (1'b0),                                   // (terminated)
		.reset_req_in8  (1'b0),                                   // (terminated)
		.reset_in9      (1'b0),                                   // (terminated)
		.reset_req_in9  (1'b0),                                   // (terminated)
		.reset_in10     (1'b0),                                   // (terminated)
		.reset_req_in10 (1'b0),                                   // (terminated)
		.reset_in11     (1'b0),                                   // (terminated)
		.reset_req_in11 (1'b0),                                   // (terminated)
		.reset_in12     (1'b0),                                   // (terminated)
		.reset_req_in12 (1'b0),                                   // (terminated)
		.reset_in13     (1'b0),                                   // (terminated)
		.reset_req_in13 (1'b0),                                   // (terminated)
		.reset_in14     (1'b0),                                   // (terminated)
		.reset_req_in14 (1'b0),                                   // (terminated)
		.reset_in15     (1'b0),                                   // (terminated)
		.reset_req_in15 (1'b0)                                    // (terminated)
	);

endmodule
